pipeline {
  agent any
 
  tools {nodejs "nodejs10.3.0"}
 
  stages {
    stage('Build') {
      steps {
        sh 'npm i --force; npm audit fix ; npm update'
	def source="deploy/tsjs-sirius-suite-wallet-library/"
	def destination="node_modules"
	sh 'scp -rv ${source} ${destination}'
      }
    }
  }
}
