pipeline {
  agent any
 
  tools {nodejs "nodejs10.3.0"}
 
  stages {
    stage('install packages and deps') {
      steps {
        sh 'npm i --force; npm audit fix ; npm update'
	sh 'cp -rv deploy/tsjs-sirius-suite-wallet-library/ node_modules/'
	sh 'npm run build'
      }
    }
  }
}
